run:
  skip-dirs:
    - .pixi
linters:
  disable-all: true
  enable:
    - deadcode
    - gas
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - nakedret
    - structcheck
    - typecheck
    - unparam
    - unused
    - varcheck
