[project]
name = "xray"
version = "0.1.0"
description = "Add a short description here"
authors = ["The SaaS Company <<founder@datasherlock.io>>"]
channels = ["conda-forge"]
platforms = [ "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
# Dev dependencies
pre-commit = "~=3.3.0"

go = "=1.22"